# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [113]:
# Given:
numbers_x = [10, 20, 30, 40, 10]


def FirstLastSame(array1):
    if array1[-1]==array1[-1] and array1[0]==array1[0]:
        print("Given list: ",array1)
        return True
    else :
        print("Given list: ",array1)
        return False
    
FirstLastSame(numbers_x)
# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False

Given list:  [10, 20, 30, 40, 10]


True





# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [12]:
#code here
import numpy as np
array1=np.arange(16).reshape(4,4)
array2=np.arange(16,32).reshape(4,4)
add=array1+array2
print("Addition :\n",add)
mul=array1*array2
print("\nMultipication :\n",mul)

Addition :
 [[16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]

Multipication :
 [[  0  17  36  57]
 [ 80 105 132 161]
 [192 225 260 297]
 [336 377 420 465]]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [15]:
#code here
array1=np.arange(16)
print ("\nBefore reshape : \n",array1)
array1=array1.reshape(4,4)
print("\nAfter reshape : \n",array1)


Before reshape : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

After reshape : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [33]:

shopping_cart = []
AvailableProducts=["hello","hehe","huhu","hapatatis"]

print("Welcome to the Shopping Cart App!")
x="Available Products :\n"
for i in range (len(AvailableProducts)):
    x+=str(i+1)+AvailableProducts[i]+'\n'




while True:


    print(x)
    choice = input("Enter the number of the product you want to add to the cart (or 'q' to quit):\n ")


    if choice.lower() == 'q':
        break


    try:
        choice = int(choice)
        if choice not in range(1, len(AvailableProducts)+1):
            raise ValueError("Invalid choice. Please enter a number between 1 and "+str(len(AvailableProducts))+".")
    except ValueError as e:
        print(e)
        continue

    shopping_cart.append(AvailableProducts[choice-1])


    print(f"{AvailableProducts[choice-1]} added to the shopping cart.")


print("\nShopping Cart Contents:")
i=1
for item in shopping_cart:
    print(str(i)+" . "+item)
    i+=1


print("Thank you for using the Shopping Cart App!")




Welcome to the Shopping Cart App!
Available Products :
1hello
2hehe
3huhu
4hapatatis

hapatatis added to the shopping cart.
Available Products :
1hello
2hehe
3huhu
4hapatatis

hapatatis added to the shopping cart.
Available Products :
1hello
2hehe
3huhu
4hapatatis

hapatatis added to the shopping cart.
Available Products :
1hello
2hehe
3huhu
4hapatatis

hapatatis added to the shopping cart.
Available Products :
1hello
2hehe
3huhu
4hapatatis

hapatatis added to the shopping cart.
Available Products :
1hello
2hehe
3huhu
4hapatatis


Shopping Cart Contents:
1 . hapatatis
2 . hapatatis
3 . hapatatis
4 . hapatatis
5 . hapatatis
Thank you for using the Shopping Cart App!


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [36]:
#code here
def ClasifyEmails(emails:list):
    dict={"important":["urgent", "important", "critical", "action required", "priority", "deadline", "time-sensitive", "emergency", "vital", "crucial", "essential", "mandatory", "imperative", "serious", "attention", "requirement", "necessary", "critical update", "must read", "response needed", "important notice", "critical alert", "key information", "important message", "urgent action", "important reminder", "urgent notice", "important information", "important update", "must respond", "important announcement", "attention required", "important details", "action needed", "important instructions", "critical situation", "high priority", "important task", "important event", "emergency situation", "action required", "important news", "important development", "critical issue", "important communication", "important memo", "critical matter"],
          "Promotions":["sale", "deal", "discount", "offer", "promotion", "exclusive", "limited time", "special", "save", "clearance", "flash sale", "bargain", "discounted", "promo code", "savings", "special offer", "discount code", "hot deal", "unbeatable", "lowest price", "best price", "buy one get one", "free shipping", "super sale", "discounted price", "amazing deal", "huge savings", "extra savings", "lowest rates", "best deal", "discount offer", "deal of the day", "promo offer", "exclusive deal", "lowest cost", "lowest prices of the season", "special promotion", "one-time offer", "price drop", "lowest fees", "special savings", "discounted rates", "clearance sale", "lowest fares", "ultimate savings", "big savings", "price reduction", "mega sale"],
          "Spam":["lottery", "prize", "free", "click here", "unsubscribe", "viagra", "earn money", "guaranteed", "credit card", "online pharmacy", "weight loss", "work from home", "meet singles", "increase sales", "multi-level marketing", "investment", "cash", "free access", "income", "millions", "earn per week", "get paid", "marketing solution", "money", "no cost", "offer", "promise", "save big money", "save up to", "this isn't a scam", "thousands", "weekend getaway", "win", "winner", "winning", "work at home", "you are a winner", "you have been selected", "your income", "zero cost", "$$$", "100% satisfied", "50% off", "amazing", "apply now", "as seen on", "be your own boss", "big bucks", "billions", "cash bonus", "cashcashcash"]}
    classify={"important":[],
              "Promotions":[],
              "Spam":[]
              }
    for i in emails:
        imp=0
        pro=0
        spm=0
        x=i.split()
        for z in range(50):
            if dict['important'][i] in x:
                imp+=1
            if dict['Promotions'][i] in x:
                pro+=1
            if dict['Spam'][i] in x:
                spm+=1
        if imp>pro and imp>spm:
            classify["important"].append()
        elif pro>spm:
            classify["Promotions"].append()
        else:
            classify["Spam"].append()
    return classify


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [39]:
#code here
eSpdict={
    "hello": "hola",
    "goodbye": "adiós",
    "thank you": "gracias",
    "please": "por favor",
    "yes": "sí",
    "no": "no",
    "friend": "amigo/amiga",
    "family": "familia",
    "love": "amor",
    "water": "agua",
    "food": "comida",
    "house": "casa",
    "car": "coche/auto",
    "book": "libro",
    "computer": "computadora",
    "school": "escuela",
    "work": "trabajo",
    "money": "dinero",
    "time": "tiempo",
    "day": "día",
    "night": "noche",
    "week": "semana",
    "month": "mes",
    "year": "año",
    "color": "color",
    "music": "música",
    "sun": "sol",
    "moon": "luna"
    }
while True:
    word=input("enter a word you want translated in spanish else enter q:")
    try:
        print(eSpdict[word])
    except KeyError:
        if word=='q':
            break
        print("The word you put in does not exist in my dictionary")

luna
hola
The word you put in does not exist in my dictionary
The word you put in does not exist in my dictionary
The word you put in does not exist in my dictionary
The word you put in does not exist in my dictionary


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [40]:
import pandas as pd
dataset=pd.read_csv("https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv")

In [44]:
dataset

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [124]:
print("Global sales sum : ",dataset['Global_Sales'].sum())

print("item with max global sales : ",dataset.loc[dataset['Global_Sales'].idxmax(),"Name"])

print("\nAverage sales wrt to regions : ")
List=['NA_Sales',"EU_Sales","JP_Sales","Other_Sales","Global_Sales"]
for i in List:
    print("Average of "+i+" : "+str(dataset[i].mean()))
List1=dataset["Genre"].unique()

print("\nTop 5 Genre : ")
dict={}
for i in List1:
   dict[(dataset.groupby('Genre').get_group(i)["Global_Sales"].sum())]=i
x=list(dict .keys())
x=np.sort(x, kind='quicksort')[::-1]
for i in range (5):
    print(dict[x[i]])

print("genre game sales in each reagion : ")
totalInAmerica=0
areaname="NA_Sales"
genreName=''

for i in List1:

    print(i,":")
    for j in List:
        print("    sales in "+j+' :'+str(dataset.groupby('Genre').get_group(i)[j].sum()))
        if j==areaname:
            if totalInAmerica<dataset.groupby('Genre').get_group(i)[j].sum():
                totalInAmerica=dataset.groupby('Genre').get_group(i)[j].sum()
                genreName=i

print ("\n the genre most liked in america is ",genreName)

print('\n last ten elements of the dataframe : ')
dataset.tail(10)

List1=dataset["Platform"].unique()
print("\nTop 3 Genre : ")
dict={}
for i in List1:
   dict[(dataset.groupby("Platform").get_group(i)["Global_Sales"].sum())]=i
x=list(dict .keys())
x=np.sort(x, kind='quicksort')[::-1]
for i in range (3):
    print(dict[x[i]])

List1=dataset["Genre"].unique()
print ("Genre percentage : ")
for i in List1:
    print("     "+i+"   : "+str( dataset.groupby('Genre').get_group(i)["Global_Sales"].sum()/dataset['Global_Sales'].sum()*100))


print("correlation coefficient : ",dataset['NA_Sales'].corr(dataset['EU_Sales']))





Global sales sum :  8920.44
item with max global sales :  Wii Sports

Average sales wrt to regions : 
Average of NA_Sales : 0.26466742981082064
Average of EU_Sales : 0.14665200626581515
Average of JP_Sales : 0.077781660441017
Average of Other_Sales : 0.0480630196409206
Average of Global_Sales : 0.5374406555006628

Top 5 Genre : 
Action
Sports
Shooter
Role-Playing
Platform
genre game sales in each reagion : 
Sports :
    sales in NA_Sales :683.35
    sales in EU_Sales :376.85
    sales in JP_Sales :135.37
    sales in Other_Sales :134.97
    sales in Global_Sales :1330.93
Platform :
    sales in NA_Sales :447.05
    sales in EU_Sales :201.63000000000002
    sales in JP_Sales :130.77
    sales in Other_Sales :51.589999999999996
    sales in Global_Sales :831.37
Racing :
    sales in NA_Sales :359.41999999999996
    sales in EU_Sales :238.39000000000001
    sales in JP_Sales :56.68999999999999
    sales in Other_Sales :77.27000000000001
    sales in Global_Sales :732.04
Role-Playing :
   